### ISSUE TITLE
Question on the online learning for testing

### ISSUE THREAD

**Issue by Reagan1311** [scutpaul/DANet#1]
Hi, thanks for sharing the code. I have tested the provided pre-trained model in group 0, and got results with F: 40.22 & J: 41.54, which are close to the results in Table 1.

I guess these are the results without online learning. However, when I implement online learning with the default setting to finetune the result, the performance degrades a lot (F: 26.18 & J: 8.14).  Why would this happen?

I use the following command:
`python test_DAN.py --test_best --finetune --group 1`

**Comment by scutpaul** [comment]
In online learning, we only finetune and test for one class at a time, so we need to specify the class idx. The setting parameter is `--finetune_idx`. The result of your test is the result of default class idx 1 in group 1. In addition, you can set different finetune parameters for different classes to get better results.
