### ISSUE TITLE
A question about the testing setting

### ISSUE THREAD

**Issue by maobj** [scutpaul/DANet#3]
Thank you for sharing your code for this good work. I want to consult that how to get the testing performance of query video. Is it calculated by several frames or all frames in the video? In your code in test_DAN.py, it seems like only calculated in 5 frames? Hoping to receive your reply.

**Comment by scutpaul** [comment]
Hi, we test all frames in the video. 
The code for testing a video is located at 
https://github.com/scutpaul/DANet/blob/f0bc57d9b2641c4dda9ce70e2c6f240ce2789069/test_DAN.py#L137

We slice the tested video and input several frames to the network at a time.
https://github.com/scutpaul/DANet/blob/f0bc57d9b2641c4dda9ce70e2c6f240ce2789069/test_DAN.py#L152-L158
