### ISSUE TITLE
Hello! Why did I get a evaluation score instead of predicted video?

### ISSUE THREAD

**Issue by 459737087** [scutpaul/DANet#5]
I was so confused that there is not any video generating.
and I received the evaluation score
![截屏2021-12-22 下午4 56 40](https://user-images.githubusercontent.com/54131759/147065290-bd5da186-9095-4994-a92f-8e27a2d24ce5.png)

**Comment by scutpaul** [comment]
Hi, you can get the predicted maps of the test video in: https://github.com/scutpaul/DANet/blob/f0bc57d9b2641c4dda9ce70e2c6f240ce2789069/test_DAN.py#L162

**Comment by 459737087** [comment]
I try it,but it doesn't work , in 
for index, data in enumerate(test_dataloader):
this code didn't work,there is not any mask predicted.
and in YoutubeVOS.py, __getitem__ function didn't work

**Comment by scutpaul** [comment]
Hi, you should be able to read and test the data by following the instructions.
You can do the following checks:
1. Whether the dataset is downloaded and extracted to the appropriate path (including labels and images)
2. Check whether the path of the project is changed to your local path:
https://github.com/scutpaul/DANet/blob/f0bc57d9b2641c4dda9ce70e2c6f240ce2789069/libs/config/DAN_config.py#L10
3. Check if ann_file has been read:
https://github.com/scutpaul/DANet/blob/f0bc57d9b2641c4dda9ce70e2c6f240ce2789069/libs/dataset/YoutubeVOS.py#L63

If you still have questions after checking, please feel free to contact me!
