### ISSUE TITLE
question about Experiments part of the paper

### ISSUE THREAD

**Issue by nankepan** [scutpaul/DANet#6]
First of all, thanks for your great work.

I have a question about the Experiments part of the paper. Paper said " We run the experiment 5 times for each fold and report the average performance to ensure the confidence of the results." Consider that the support set is randomly select when training as well as testing. So I wonder if this means that train 5 times and test 1 time, or train 1 time and test 5 times. 

I will be appreciated for your reply as soon as possible, thank you very much!

**Comment by scutpaul** [comment]
hi, we train 1 time and test 5 times for each fold.

**Comment by nankepan** [comment]
Got it.Thanks for your reply!

**Comment by nankepan** [comment]
Another question. I wonder if the result based on epoch_100.pth.tar or model_best.pth.tar
